const modelList = [
  {
    name: "科技展厅",
    key: "glb-27",
    fileType: "glb",
    id: 27,
    animation: false,
    filePath: "models/glb/glb-27.glb",
    coverUrl: "images/model-icon/21.jpg",
    modelType: "model",
    decomposeName: "glb-27",
  },
  {
    name: "电脑",
    key: "glb-28",
    fileType: "glb",
    id: 28,
    animation: false,
    filePath: "models/glb/glb-28.glb",
    coverUrl: "images/model-icon/19.png",
    modelType: "model",
    decomposeName: "glb-28",
  },
  {
    name: "植物",
    key: "glb-29",
    fileType: "glb",
    id: 29,
    animation: false,
    filePath: "models/glb/glb-29.glb",
    coverUrl: "images/model-icon/20.png",
    modelType: "model",
    decomposeName: "glb-29",
  },
];

// 几何体模型列表
const geometryModelList = [
  {
    id: 30,
    name: "立方体",
    modelType: "geometry",
    type: "BoxGeometry",
    width: 1, // X轴上面的宽度
    height: 1, // Y轴上面的高度
    depth: 1, // 轴上面的深度
    widthSegments: 1, //宽度的分段数
    heightSegments: 1, //高度的分段数
    depthSegments: 1, //深度的分段数
  },
  {
    id: 31,
    name: "胶囊",
    modelType: "geometry",
    type: "CapsuleGeometry",
    radius: 0.5, // 胶囊半径
    length: 0.5, //中间区域的长度
    capSegments: 10, // 构造盖子的曲线部分的个数
    radialSegments: 10, //覆盖胶囊圆周的分离的面的个数
  },
  {
    id: 32,
    name: "圆形",
    modelType: "geometry",
    type: "CircleGeometry",
    radius: 0.5, // 半径
    segments: 32, //分段（三角面）的数量
    thetaStart: 0, // 第一个分段的起始角度
    thetaLength: 6.44, //圆形扇区的中心角
  },
  {
    id: 33,
    name: "圆锥",
    modelType: "geometry",
    type: "ConeGeometry",
    radius: 0.5, // 半径
    height: 1, //圆锥的高度
    radialSegments: 8, // 圆锥侧面周围的分段数
    heightSegments: 1, //圆形扇区的中心角
    openEnded: false, //指明该圆锥的底面是开放的还是封顶的
    thetaStart: 0,
    thetaLength: 6.44, //圆形扇区的中心角
  },
  {
    id: 35,
    name: "十二面体",
    modelType: "geometry",
    type: "DodecahedronGeometry",
    radius: 0.5,
    detail: 0,
  },
  {
    id: 36,
    name: "二十面体",
    modelType: "geometry",
    type: "IcosahedronGeometry",
    radius: 0.5,
    detail: 0,
  },
  {
    id: 37,
    name: "八面体",
    modelType: "geometry",
    type: "OctahedronGeometry",
    radius: 0.5,
    detail: 0,
  },
  {
    id: 38,
    name: "平面",
    modelType: "geometry",
    type: "PlaneGeometry",
    width: 1, // X轴上面的宽度
    height: 1, // Y轴上面的高度
    widthSegments: 1, //宽度的分段数
    heightSegments: 1, //高度的分段数
  },
  {
    id: 40,
    name: "球",
    modelType: "geometry",
    type: "SphereGeometry",
    radius: 0.5,
    widthSegments: 32,
    heightSegments: 16,
    phiStart: 0,
    phiLength: 6,
    thetaStart: 0,
    thetaLength: 7,
  },
  {
    id: 41,
    name: "四面体",
    modelType: "geometry",
    type: "TetrahedronGeometry",
    radius: 0.5,
    detail: 0,
  },
  {
    id: 42,
    name: "圆环",
    modelType: "geometry",
    type: "TorusGeometry",
    radius: 0.5,
    tube: 0.1,
    radialSegments: 15,
    tubularSegments: 15,
    arc: 6.32,
  },
];

// 图片素材
const hotspotImageList = [
  {
    id: "821436",
    modelType: "hotspot",
    fileType: "image",
    anchor_id: "0",
    cid: "12625",
    name: "商务长图",
    fileName: "643d06e38d7a3.jpg",
    thumb_status: "0",
    size: "193244",
    size_for_small: "0",
    size_for_big: "0",
    width: "2400",
    height: "600",
    create_time: "2023-09-07 19:14",
    update_time: "2023-09-07 19:14",
    status: "1",
    deleted: "0",
    public_show: "0",
    pool_id: "0",
    body_compound_id: "0",
    latitude: "0",
    longitude: "0",
    ip: "",
    md5: "",
    iptm_id: "0",
    from_anchor_id: "0",
    FNumber: "",
    ExposureTime: "",
    ISO: "",
    mime_type: "",
    shoot_time: "0",
    method: "0",
    tags: "",
    sale_status: "0",
    sale_update_time: "0",
    sale_on_time: "0",
    sale_info: "",
    price: "0.00",
    agent_modify: "0",
    seq_status: "0",
    file_size: "188.71 KB",
    coverUrl: "images/hotspot/643d06e38d7a3.jpg",
    cover_url: "",
    categoryName: "商务办公",
  },
  {
    id: "821737",
    modelType: "hotspot",
    fileType: "image",
    anchor_id: "0",
    cid: "12625",
    name: "思考",
    fileName: "643d0f3af18e5.jpg",
    thumb_status: "0",
    size: "76389",
    size_for_small: "0",
    size_for_big: "0",
    width: "900",
    height: "600",
    create_time: "2023-04-17 17:19",
    update_time: "2023-04-17 17:20",
    status: "1",
    deleted: "0",
    public_show: "0",
    pool_id: "0",
    body_compound_id: "0",
    latitude: "0",
    longitude: "0",
    ip: "",
    md5: "",
    iptm_id: "0",
    from_anchor_id: "0",
    FNumber: "",
    ExposureTime: "",
    ISO: "",
    mime_type: "",
    shoot_time: "0",
    method: "0",
    tags: "",
    sale_status: "0",
    sale_update_time: "0",
    sale_on_time: "0",
    sale_info: "",
    price: "0.00",
    agent_modify: "0",
    seq_status: "0",
    file_size: "74.6 KB",
    coverUrl: "images/hotspot/643d0f3af18e5.jpg",
    cover_url: "",
    categoryName: "商务办公",
  },
  {
    id: "821738",
    modelType: "hotspot",
    fileType: "image",
    anchor_id: "0",
    cid: "12625",
    name: "想法",
    fileName: "643d0f3b07f0f.jpg",
    thumb_status: "0",
    size: "98329",
    size_for_small: "0",
    size_for_big: "0",
    width: "900",
    height: "600",
    create_time: "2023-04-17 17:19",
    update_time: "2023-04-17 17:20",
    status: "1",
    deleted: "0",
    public_show: "0",
    pool_id: "0",
    body_compound_id: "0",
    latitude: "0",
    longitude: "0",
    ip: "",
    md5: "",
    iptm_id: "0",
    from_anchor_id: "0",
    FNumber: "",
    ExposureTime: "",
    ISO: "",
    mime_type: "",
    shoot_time: "0",
    method: "0",
    tags: "",
    sale_status: "0",
    sale_update_time: "0",
    sale_on_time: "0",
    sale_info: "",
    price: "0.00",
    agent_modify: "0",
    seq_status: "0",
    file_size: "96.02 KB",
    coverUrl: "images/hotspot/643d0f3b07f0f.jpg",
    cover_url: "",
    categoryName: "商务办公",
  },
  {
    id: "821735",
    modelType: "hotspot",
    fileType: "image",
    anchor_id: "0",
    cid: "12625",
    name: "创意",
    fileName: "643d0f3a76f99.jpg",
    thumb_status: "0",
    size: "82941",
    size_for_small: "0",
    size_for_big: "0",
    width: "900",
    height: "600",
    create_time: "2023-04-17 17:19",
    update_time: "2023-04-17 17:20",
    status: "1",
    deleted: "0",
    public_show: "0",
    pool_id: "0",
    body_compound_id: "0",
    latitude: "0",
    longitude: "0",
    ip: "",
    md5: "",
    iptm_id: "0",
    from_anchor_id: "0",
    FNumber: "",
    ExposureTime: "",
    ISO: "",
    mime_type: "",
    shoot_time: "0",
    method: "0",
    tags: "",
    sale_status: "0",
    sale_update_time: "0",
    sale_on_time: "0",
    sale_info: "",
    price: "0.00",
    agent_modify: "0",
    seq_status: "0",
    file_size: "81 KB",
    coverUrl: "images/hotspot/643d0f3a76f99.jpg",
    cover_url: "",
    categoryName: "商务办公",
  },
  {
    id: "821736",
    modelType: "hotspot",
    fileType: "image",
    anchor_id: "0",
    cid: "12625",
    name: "背影",
    fileName: "643d0f3a846dd.jpg",
    thumb_status: "0",
    size: "74073",
    size_for_small: "0",
    size_for_big: "0",
    width: "900",
    height: "600",
    create_time: "2023-04-17 17:19",
    update_time: "2023-04-17 17:20",
    status: "1",
    deleted: "0",
    public_show: "0",
    pool_id: "0",
    body_compound_id: "0",
    latitude: "0",
    longitude: "0",
    ip: "",
    md5: "",
    iptm_id: "0",
    from_anchor_id: "0",
    FNumber: "",
    ExposureTime: "",
    ISO: "",
    mime_type: "",
    shoot_time: "0",
    method: "0",
    tags: "",
    sale_status: "0",
    sale_update_time: "0",
    sale_on_time: "0",
    sale_info: "",
    price: "0.00",
    agent_modify: "0",
    seq_status: "0",
    file_size: "72.34 KB",
    coverUrl: "images/hotspot/643d0f3a846dd.jpg",
    cover_url: "",
    categoryName: "商务办公",
  },
  {
    id: "821731",
    modelType: "hotspot",
    fileType: "image",
    anchor_id: "0",
    cid: "12625",
    name: "商务长图2",
    fileName: "643d0f0d033d3.jpg",
    thumb_status: "0",
    size: "69030",
    size_for_small: "0",
    size_for_big: "0",
    width: "2000",
    height: "500",
    create_time: "2023-04-17 17:19",
    update_time: "2023-04-17 17:19",
    status: "1",
    deleted: "0",
    public_show: "0",
    pool_id: "0",
    body_compound_id: "0",
    latitude: "0",
    longitude: "0",
    ip: "",
    md5: "",
    iptm_id: "0",
    from_anchor_id: "0",
    FNumber: "",
    ExposureTime: "",
    ISO: "",
    mime_type: "",
    shoot_time: "0",
    method: "0",
    tags: "",
    sale_status: "0",
    sale_update_time: "0",
    sale_on_time: "0",
    sale_info: "",
    price: "0.00",
    agent_modify: "0",
    seq_status: "0",
    file_size: "67.41 KB",
    coverUrl: "images/hotspot/643d0f0d033d3.jpg",
    cover_url: "",
    categoryName: "商务办公",
  },
  {
    id: "821730",
    modelType: "hotspot",
    fileType: "image",
    anchor_id: "0",
    cid: "12625",
    name: "商务长图3",
    fileName: "643d0f0c6b19d.jpg",
    thumb_status: "0",
    size: "84869",
    size_for_small: "0",
    size_for_big: "0",
    width: "2000",
    height: "575",
    create_time: "2023-04-17 17:19",
    update_time: "2023-04-17 17:19",
    status: "1",
    deleted: "0",
    public_show: "0",
    pool_id: "0",
    body_compound_id: "0",
    latitude: "0",
    longitude: "0",
    ip: "",
    md5: "",
    iptm_id: "0",
    from_anchor_id: "0",
    FNumber: "",
    ExposureTime: "",
    ISO: "",
    mime_type: "",
    shoot_time: "0",
    method: "0",
    tags: "",
    sale_status: "0",
    sale_update_time: "0",
    sale_on_time: "0",
    sale_info: "",
    price: "0.00",
    agent_modify: "0",
    seq_status: "0",
    file_size: "82.88 KB",
    coverUrl: "images/hotspot/643d0f0c6b19d.jpg",
    cover_url: "",
    categoryName: "商务办公",
  },
  {
    id: "821727",
    modelType: "hotspot",
    fileType: "image",
    anchor_id: "0",
    cid: "12625",
    name: "碰拳",
    fileName: "643d0ebe106be.jpg",
    thumb_status: "0",
    size: "105150",
    size_for_small: "0",
    size_for_big: "0",
    width: "1200",
    height: "1200",
    create_time: "2023-04-17 17:17",
    update_time: "2023-04-17 17:18",
    status: "1",
    deleted: "0",
    public_show: "0",
    pool_id: "0",
    body_compound_id: "0",
    latitude: "0",
    longitude: "0",
    ip: "",
    md5: "",
    iptm_id: "0",
    from_anchor_id: "0",
    FNumber: "",
    ExposureTime: "",
    ISO: "",
    mime_type: "",
    shoot_time: "0",
    method: "0",
    tags: "",
    sale_status: "0",
    sale_update_time: "0",
    sale_on_time: "0",
    sale_info: "",
    price: "0.00",
    agent_modify: "0",
    seq_status: "0",
    file_size: "102.69 KB",
    coverUrl: "images/hotspot/643d0ebe106be.jpg",
    cover_url: "",
    categoryName: "商务办公",
  },
  {
    id: "821728",
    modelType: "hotspot",
    fileType: "image",
    anchor_id: "0",
    cid: "12625",
    name: "握手",
    fileName: "643d0ebe57bc6.jpg",
    thumb_status: "0",
    size: "127089",
    size_for_small: "0",
    size_for_big: "0",
    width: "1200",
    height: "1200",
    create_time: "2023-04-17 17:17",
    update_time: "2023-04-17 17:18",
    status: "1",
    deleted: "0",
    public_show: "0",
    pool_id: "0",
    body_compound_id: "0",
    latitude: "0",
    longitude: "0",
    ip: "",
    md5: "",
    iptm_id: "0",
    from_anchor_id: "0",
    FNumber: "",
    ExposureTime: "",
    ISO: "",
    mime_type: "",
    shoot_time: "0",
    method: "0",
    tags: "",
    sale_status: "0",
    sale_update_time: "0",
    sale_on_time: "0",
    sale_info: "",
    price: "0.00",
    agent_modify: "0",
    seq_status: "0",
    file_size: "124.11 KB",
    coverUrl: "images/hotspot/643d0ebe57bc6.jpg",
    cover_url: "",
    categoryName: "商务办公",
  },
  {
    id: "821729",
    modelType: "hotspot",
    fileType: "image",
    anchor_id: "0",
    cid: "12625",
    name: "科技",
    fileName: "643d0ebe488bf.jpg",
    thumb_status: "0",
    size: "159820",
    size_for_small: "0",
    size_for_big: "0",
    width: "1200",
    height: "1200",
    create_time: "2023-04-17 17:17",
    update_time: "2023-04-17 17:18",
    status: "1",
    deleted: "0",
    public_show: "0",
    pool_id: "0",
    body_compound_id: "0",
    latitude: "0",
    longitude: "0",
    ip: "",
    md5: "",
    iptm_id: "0",
    from_anchor_id: "0",
    FNumber: "",
    ExposureTime: "",
    ISO: "",
    mime_type: "",
    shoot_time: "0",
    method: "0",
    tags: "",
    sale_status: "0",
    sale_update_time: "0",
    sale_on_time: "0",
    sale_info: "",
    price: "0.00",
    agent_modify: "0",
    seq_status: "0",
    file_size: "156.07 KB",
    coverUrl: "images/hotspot/643d0ebe488bf.jpg",
    cover_url: "",
    categoryName: "商务办公",
  },
  {
    id: "821725",
    modelType: "hotspot",
    fileType: "image",
    anchor_id: "0",
    cid: "12625",
    name: "交易",
    fileName: "643d0ebdb87eb.jpg",
    thumb_status: "0",
    size: "92214",
    size_for_small: "0",
    size_for_big: "0",
    width: "1200",
    height: "1200",
    create_time: "2023-04-17 17:17",
    update_time: "2023-04-17 17:18",
    status: "1",
    deleted: "0",
    public_show: "0",
    pool_id: "0",
    body_compound_id: "0",
    latitude: "0",
    longitude: "0",
    ip: "",
    md5: "",
    iptm_id: "0",
    from_anchor_id: "0",
    FNumber: "",
    ExposureTime: "",
    ISO: "",
    mime_type: "",
    shoot_time: "0",
    method: "0",
    tags: "",
    sale_status: "0",
    sale_update_time: "0",
    sale_on_time: "0",
    sale_info: "",
    price: "0.00",
    agent_modify: "0",
    seq_status: "0",
    file_size: "90.05 KB",
    coverUrl: "images/hotspot/643d0ebdb87eb.jpg",
    cover_url: "",
    categoryName: "商务办公",
  },
  {
    id: "821726",
    modelType: "hotspot",
    fileType: "image",
    anchor_id: "0",
    cid: "12625",
    name: "计算",
    fileName: "643d0ebdd515b.jpg",
    thumb_status: "0",
    size: "119735",
    size_for_small: "0",
    size_for_big: "0",
    width: "1200",
    height: "1200",
    create_time: "2023-04-17 17:17",
    update_time: "2023-04-17 17:18",
    status: "1",
    deleted: "0",
    public_show: "0",
    pool_id: "0",
    body_compound_id: "0",
    latitude: "0",
    longitude: "0",
    ip: "",
    md5: "",
    iptm_id: "0",
    from_anchor_id: "0",
    FNumber: "",
    ExposureTime: "",
    ISO: "",
    mime_type: "",
    shoot_time: "0",
    method: "0",
    tags: "",
    sale_status: "0",
    sale_update_time: "0",
    sale_on_time: "0",
    sale_info: "",
    price: "0.00",
    agent_modify: "0",
    seq_status: "0",
    file_size: "116.93 KB",
    coverUrl: "images/hotspot/643d0ebdd515b.jpg",
    cover_url: "",
    categoryName: "商务办公",
  },
  {
    id: "821439",
    modelType: "hotspot",
    fileType: "image",
    anchor_id: "0",
    cid: "12625",
    name: "空间",
    fileName: "643d0703263b6.jpg",
    thumb_status: "0",
    size: "113591",
    size_for_small: "0",
    size_for_big: "0",
    width: "1200",
    height: "1200",
    create_time: "2023-04-17 16:44",
    update_time: "2023-04-17 16:45",
    status: "1",
    deleted: "0",
    public_show: "0",
    pool_id: "0",
    body_compound_id: "0",
    latitude: "0",
    longitude: "0",
    ip: "",
    md5: "",
    iptm_id: "0",
    from_anchor_id: "0",
    FNumber: "",
    ExposureTime: "",
    ISO: "",
    mime_type: "",
    shoot_time: "0",
    method: "0",
    tags: "",
    sale_status: "0",
    sale_update_time: "0",
    sale_on_time: "0",
    sale_info: "",
    price: "0.00",
    agent_modify: "0",
    seq_status: "0",
    file_size: "110.93 KB",
    coverUrl: "images/hotspot/643d0703263b6.jpg",
    cover_url: "",
    categoryName: "商务办公",
  },
  {
    id: "821440",
    modelType: "hotspot",
    fileType: "image",
    anchor_id: "0",
    cid: "12625",
    name: "AI办公",
    fileName: "643d0703375f8.jpg",
    thumb_status: "0",
    size: "103833",
    size_for_small: "0",
    size_for_big: "0",
    width: "1200",
    height: "1200",
    create_time: "2023-04-17 16:44",
    update_time: "2023-04-17 16:45",
    status: "1",
    deleted: "0",
    public_show: "0",
    pool_id: "0",
    body_compound_id: "0",
    latitude: "0",
    longitude: "0",
    ip: "",
    md5: "",
    iptm_id: "0",
    from_anchor_id: "0",
    FNumber: "",
    ExposureTime: "",
    ISO: "",
    mime_type: "",
    shoot_time: "0",
    method: "0",
    tags: "",
    sale_status: "0",
    sale_update_time: "0",
    sale_on_time: "0",
    sale_info: "",
    price: "0.00",
    agent_modify: "0",
    seq_status: "0",
    file_size: "101.4 KB",
    coverUrl: "images/hotspot/643d0703375f8.jpg",
    cover_url: "",
    categoryName: "商务办公",
  },
  {
    id: "821437",
    modelType: "hotspot",
    fileType: "image",
    anchor_id: "0",
    cid: "12625",
    name: "霓虹城市",
    fileName: "643d070244c18.jpg",
    thumb_status: "0",
    size: "138918",
    size_for_small: "0",
    size_for_big: "0",
    width: "1200",
    height: "1200",
    create_time: "2023-04-17 16:44",
    update_time: "2023-04-17 16:45",
    status: "1",
    deleted: "0",
    public_show: "0",
    pool_id: "0",
    body_compound_id: "0",
    latitude: "0",
    longitude: "0",
    ip: "",
    md5: "",
    iptm_id: "0",
    from_anchor_id: "0",
    FNumber: "",
    ExposureTime: "",
    ISO: "",
    mime_type: "",
    shoot_time: "0",
    method: "0",
    tags: "",
    sale_status: "0",
    sale_update_time: "0",
    sale_on_time: "0",
    sale_info: "",
    price: "0.00",
    agent_modify: "0",
    seq_status: "0",
    file_size: "135.66 KB",
    coverUrl: "images/hotspot/643d070244c18.jpg",
    cover_url: "",
    categoryName: "商务办公",
  },
  {
    id: "821438",
    modelType: "hotspot",
    fileType: "image",
    anchor_id: "0",
    cid: "12625",
    name: "炫幻",
    fileName: "643d07029f3e0.jpg",
    thumb_status: "0",
    size: "193103",
    size_for_small: "0",
    size_for_big: "0",
    width: "1200",
    height: "1200",
    create_time: "2023-04-17 16:44",
    update_time: "2023-04-17 16:45",
    status: "1",
    deleted: "0",
    public_show: "0",
    pool_id: "0",
    body_compound_id: "0",
    latitude: "0",
    longitude: "0",
    ip: "",
    md5: "",
    iptm_id: "0",
    from_anchor_id: "0",
    FNumber: "",
    ExposureTime: "",
    ISO: "",
    mime_type: "",
    shoot_time: "0",
    method: "0",
    tags: "",
    sale_status: "0",
    sale_update_time: "0",
    sale_on_time: "0",
    sale_info: "",
    price: "0.00",
    agent_modify: "0",
    seq_status: "0",
    file_size: "188.58 KB",
    coverUrl: "images/hotspot/643d07029f3e0.jpg",
    cover_url: "",
    categoryName: "商务办公",
  },
  {
    id: "821433",
    modelType: "hotspot",
    fileType: "image",
    anchor_id: "0",
    cid: "12625",
    name: "AI智能",
    fileName: "643d06aa22ced.jpg",
    thumb_status: "0",
    size: "66934",
    size_for_small: "0",
    size_for_big: "0",
    width: "600",
    height: "1067",
    create_time: "2023-04-17 16:43",
    update_time: "2023-04-17 16:43",
    status: "1",
    deleted: "0",
    public_show: "0",
    pool_id: "0",
    body_compound_id: "0",
    latitude: "0",
    longitude: "0",
    ip: "",
    md5: "",
    iptm_id: "0",
    from_anchor_id: "0",
    FNumber: "",
    ExposureTime: "",
    ISO: "",
    mime_type: "",
    shoot_time: "0",
    method: "0",
    tags: "",
    sale_status: "0",
    sale_update_time: "0",
    sale_on_time: "0",
    sale_info: "",
    price: "0.00",
    agent_modify: "0",
    seq_status: "0",
    file_size: "65.37 KB",
    coverUrl: "images/hotspot/643d06aa22ced.jpg",
    cover_url: "",
    categoryName: "商务办公",
  },
  {
    id: "821432",
    modelType: "hotspot",
    fileType: "image",
    anchor_id: "0",
    cid: "12625",
    name: "矩形",
    fileName: "643d06a9abb94.jpg",
    thumb_status: "0",
    size: "54905",
    size_for_small: "0",
    size_for_big: "0",
    width: "600",
    height: "1067",
    create_time: "2023-04-17 16:43",
    update_time: "2023-04-17 16:44",
    status: "1",
    deleted: "0",
    public_show: "0",
    pool_id: "0",
    body_compound_id: "0",
    latitude: "0",
    longitude: "0",
    ip: "",
    md5: "",
    iptm_id: "0",
    from_anchor_id: "0",
    FNumber: "",
    ExposureTime: "",
    ISO: "",
    mime_type: "",
    shoot_time: "0",
    method: "0",
    tags: "",
    sale_status: "0",
    sale_update_time: "0",
    sale_on_time: "0",
    sale_info: "",
    price: "0.00",
    agent_modify: "0",
    seq_status: "0",
    file_size: "53.62 KB",
    coverUrl: "images/hotspot/643d06a9abb94.jpg",
    cover_url: "",
    categoryName: "商务办公",
  },
  {
    id: "821319",
    modelType: "hotspot",
    fileType: "image",
    anchor_id: "0",
    cid: "12625",
    name: "独立办公",
    fileName: "643d05d6e4c03.jpg",
    thumb_status: "0",
    size: "68467",
    size_for_small: "0",
    size_for_big: "0",
    width: "1200",
    height: "800",
    create_time: "2023-04-17 16:39",
    update_time: "2023-04-17 16:43",
    status: "1",
    deleted: "0",
    public_show: "0",
    pool_id: "0",
    body_compound_id: "0",
    latitude: "0",
    longitude: "0",
    ip: "",
    md5: "",
    iptm_id: "0",
    from_anchor_id: "0",
    FNumber: "",
    ExposureTime: "",
    ISO: "",
    mime_type: "",
    shoot_time: "0",
    method: "0",
    tags: "",
    sale_status: "0",
    sale_update_time: "0",
    sale_on_time: "0",
    sale_info: "",
    price: "0.00",
    agent_modify: "0",
    seq_status: "0",
    file_size: "66.86 KB",
    coverUrl: "images/hotspot/643d05d6e4c03.jpg",
    cover_url: "",
    categoryName: "商务办公",
  },
  {
    id: "821320",
    modelType: "hotspot",
    fileType: "image",
    anchor_id: "0",
    cid: "12625",
    name: "监控室",
    fileName: "643d05d7264a6.jpg",
    thumb_status: "0",
    size: "90173",
    size_for_small: "0",
    size_for_big: "0",
    width: "1200",
    height: "800",
    create_time: "2023-04-17 16:39",
    update_time: "2023-04-17 16:42",
    status: "1",
    deleted: "0",
    public_show: "0",
    pool_id: "0",
    body_compound_id: "0",
    latitude: "0",
    longitude: "0",
    ip: "",
    md5: "",
    iptm_id: "0",
    from_anchor_id: "0",
    FNumber: "",
    ExposureTime: "",
    ISO: "",
    mime_type: "",
    shoot_time: "0",
    method: "0",
    tags: "",
    sale_status: "0",
    sale_update_time: "0",
    sale_on_time: "0",
    sale_info: "",
    price: "0.00",
    agent_modify: "0",
    seq_status: "0",
    file_size: "88.06 KB",
    coverUrl: "images/hotspot/643d05d7264a6.jpg",
    cover_url: "",
    categoryName: "商务办公",
  },
  {
    id: "821321",
    modelType: "hotspot",
    fileType: "image",
    anchor_id: "0",
    cid: "12625",
    name: "梦幻办公",
    fileName: "643d05d736779.jpg",
    thumb_status: "0",
    size: "94971",
    size_for_small: "0",
    size_for_big: "0",
    width: "1200",
    height: "800",
    create_time: "2023-04-17 16:39",
    update_time: "2023-04-17 16:42",
    status: "1",
    deleted: "0",
    public_show: "0",
    pool_id: "0",
    body_compound_id: "0",
    latitude: "0",
    longitude: "0",
    ip: "",
    md5: "",
    iptm_id: "0",
    from_anchor_id: "0",
    FNumber: "",
    ExposureTime: "",
    ISO: "",
    mime_type: "",
    shoot_time: "0",
    method: "0",
    tags: "",
    sale_status: "0",
    sale_update_time: "0",
    sale_on_time: "0",
    sale_info: "",
    price: "0.00",
    agent_modify: "0",
    seq_status: "0",
    file_size: "92.75 KB",
    coverUrl: "images/hotspot/643d05d736779.jpg",
    cover_url: "",
    categoryName: "商务办公",
  },
];

export { modelList, geometryModelList, hotspotImageList };
